/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.action.procurement;

import java.io.UnsupportedEncodingException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import dbconnection.MysqlCon;
import entity.AgainorderDetail;
import entity.ImportDetail;

/** 
 * MyEclipse Struts
 * Creation date: 02-05-2017
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class AgainorderDetailAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		String againorderid=request.getParameter("id");
		String againorderstate=request.getParameter("state");
		try {
			againorderstate=new String(againorderstate.getBytes("ISO-8859-1"),"utf-8");
		} catch (UnsupportedEncodingException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		try{
			MysqlCon msq=new MysqlCon();
			Connection conn=msq.connection();
			ResultSet rs=msq.query("select user.userName,againorder.againOrderTime from amc.againorder,amc.user where againorder.userID=user.userID and againorder.againorderID="+againorderid,conn);
			rs.beforeFirst();
			while(rs.next()){
				request.setAttribute("againorderid", againorderid);
				request.setAttribute("againorderstate", againorderstate);
				request.setAttribute("username", rs.getString(1));
				request.setAttribute("againordertime", rs.getDate(2)+"");
			}conn.close();
		}catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		List<AgainorderDetail> againorderdetaillist=new ArrayList<AgainorderDetail>();
		int id=0;
		try{
			MysqlCon msq=new MysqlCon();
			Connection conn=msq.connection();
			ResultSet rs=msq.query("select againorderdetail.productID,product.productName,againorderdetail.productQua from amc.againorderdetail,amc.product where againorderdetail.productID=product.productID  and againorderdetail.againorderID="+againorderid, conn);
			rs.beforeFirst();
			while(rs.next()){
				AgainorderDetail againorderdetail=new AgainorderDetail();
				id=id+1;
				againorderdetail.setNumber(id+"");
				againorderdetail.setAgainorderid(againorderid);
				againorderdetail.setProductid(rs.getInt(1)+"");
				againorderdetail.setProductname(rs.getString(2));
				againorderdetail.setProductqua(rs.getString(3));
				againorderdetaillist.add(againorderdetail);
			}conn.close();
		    request.setAttribute("againorderdetail", againorderdetaillist);
		}catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		if(againorderstate.equals("“—¥¶¿Ì")){
			return mapping.findForward("againorderview");
		}
		else{
		return mapping.findForward("againorderdetail");
		}
	}
}