/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.action.procurement;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import dbconnection.MysqlCon;
import entity.Outstock;


/** 
 * MyEclipse Struts
 * Creation date: 02-05-2017
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class OutstockListAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		List<Outstock> outstocklist=new ArrayList<Outstock>();
		int ids=0;
		try{
			MysqlCon msq=new MysqlCon();
			Connection conn=msq.connection();
			ResultSet rs=msq.query("select outstock.outstockID,outstock.orderID,user.userName,outstock.outStockTime,outstock.outStockState from amc.outstock,amc.user where outstock.userID=user.userID", conn);
		    rs.beforeFirst();
			while(rs.next()){
				ids=ids+1;
				Outstock outstock=new Outstock();
				outstock.setNumber(ids+"");
				outstock.setOutstockid(rs.getInt(1)+"");
				outstock.setOrderid(rs.getString(2)+"");
				outstock.setUsername(rs.getString(3));
				outstock.setOutstocktime(rs.getDate(4)+"");
				outstock.setOutstockstate(rs.getString(5));
				outstocklist.add(outstock);
			}
			request.setAttribute("outstocklist", outstocklist);
			conn.close();
		}catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}		return mapping.findForward("outstocklist");
		// TODO Auto-generated method stub
		
	}
}