/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.action.procurement;

import java.io.UnsupportedEncodingException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import dbconnection.MysqlCon;
import entity.OutstockDetail;

/** 
 * MyEclipse Struts
 * Creation date: 02-06-2017
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class OutstockDetailAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		String outstockid=request.getParameter("id");
		String outstockstate=request.getParameter("state");
		try {
			outstockstate=new String(outstockstate.getBytes("ISO-8859-1"),"utf-8");
		} catch (UnsupportedEncodingException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		try{
			MysqlCon msq=new MysqlCon();
			Connection conn=msq.connection();
			ResultSet rs=msq.query("select user.userName,outstock.outStockTime from amc.outstock,amc.user where outstock.userID=user.userID and outstock.outstockID="+outstockid,conn);
			rs.beforeFirst();
			while(rs.next()){
				request.setAttribute("outstockid", outstockid);
				request.setAttribute("outstockstate", outstockstate);
				request.setAttribute("username", rs.getString(1));
				request.setAttribute("outstocktime", rs.getDate(2)+"");
			}conn.close();
		}catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		List<OutstockDetail> outstockdetaillist=new ArrayList<OutstockDetail>();
		int id=0;
		try{
			MysqlCon msq=new MysqlCon();
			Connection conn=msq.connection();
			ResultSet rs=msq.query("select outstockdetail.productID,product.productName,outstockdetail.outStockNum from amc.outstockdetail,amc.product where outstockdetail.productID=product.productID  and outstockdetail.outStockID="+outstockid, conn);
			rs.beforeFirst();
			while(rs.next()){
				OutstockDetail outstockdetail=new OutstockDetail();
				id=id+1;
				outstockdetail.setNumber(id+"");
				outstockdetail.setOutstockid(outstockid);
				outstockdetail.setProductid(rs.getInt(1)+"");
				outstockdetail.setProductname(rs.getString(2));
				outstockdetail.setOutstocknum(rs.getString(3));
				outstockdetaillist.add(outstockdetail);
			}conn.close();
		    request.setAttribute("outstockdetail", outstockdetaillist);
		}catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		if(outstockstate.equals("Œ¥¥¶¿Ì"))
			return mapping.findForward("outstockdetail");
		else
			return mapping.findForward("outstockview");
	
	}
}