/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.action.procurement;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import dbconnection.MysqlCon;

/** 
 * MyEclipse Struts
 * Creation date: 02-06-2017
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class SupplierUpdate1Action extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		String id=request.getParameter("id");
		String suppliername="";
		String suppliercode="";
		String suppliermaster="";
		String supplieraddress="";
		String suppliertel="";
		String supplieremail="";
		String productrange="";
		try{
		MysqlCon msq=new MysqlCon();
		Connection conn=msq.connection();
		ResultSet rs=msq.query("select supplierName,supplierCode,supplierMaster,address,supplierTel,email,productRange from supplier where supplierID="+id,conn);
	    
			suppliername=rs.getString(1);
			suppliercode=rs.getString(2);
			suppliermaster=rs.getString(3);
			supplieraddress=rs.getString(4);
			suppliertel=rs.getString(5);
			supplieremail=rs.getString(6);
			productrange=rs.getString(7);
			conn.close();
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}	
	    request.setAttribute("supplierid",id);
	    request.setAttribute("suppliername",suppliername);
	    request.setAttribute("suppliercode",suppliercode);
	    request.setAttribute("suppliermaster",suppliermaster);
	    request.setAttribute("supplieraddress",supplieraddress);
	    request.setAttribute("suppliertel",suppliertel);
	    request.setAttribute("supplieremail",supplieremail);
	    request.setAttribute("productrange",productrange);
	    
	    
		return mapping.findForward("supplierupdate");
		
	}
}