/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.action;

import java.sql.Connection;
import java.sql.ResultSet;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import dbconnection.MysqlCon;
import struts.form.ChangePasswordForm;

/** 
 * MyEclipse Struts
 * Creation date: 02-16-2017
 * 
 * XDoclet definition:
 * @struts.action path="/changePassword" name="changePasswordForm" scope="request" validate="true"
 */
public class ChangePasswordAction extends ResultBasedAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */


	@Override
	public Result execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request) throws Exception {
		// TODO Auto-generated method stub
		ChangePasswordForm changePasswordForm = (ChangePasswordForm) form;// TODO Auto-generated method stub
		int userID = changePasswordForm.getUserID();
		String oldPassword=changePasswordForm.getOldPassword();
		String newPassword=changePasswordForm.getNewPassword();
		String confirmNewPassword = changePasswordForm.getConfirmNewPassword();
		String msg = "";
		
		if(oldPassword==""||newPassword==""||confirmNewPassword==""){
			msg="操作失败！密码不能为空，请重试。";
		}
		
		else {
			String correctOldPassword="";
			MysqlCon mysqlCon = new MysqlCon();
			Connection conn = mysqlCon.connection();
			ResultSet rs = mysqlCon.query("select password from user where userID="+userID, conn);
			if(rs!=null){
				correctOldPassword = rs.getString(1);
			}
			
			if (!oldPassword.equals(correctOldPassword)){
				msg="操作失败！原密码输入错误，请重试。";
			}
			
			else if(!newPassword.equals(confirmNewPassword)){
				msg="操作失败！确认密码与新密码不同，请重试。";
			}
			
			else if(oldPassword.equals(newPassword)){
				msg="操作失败！新密码不能与原密码相同，请重试。";
			}
			
			else{
				mysqlCon.update("update user set password='"+newPassword+"' where userID="+userID);
				msg="SUCCESS";
			}
			
		}
		
		StringResult sr = new StringResult(msg);
		return sr;
	}
}