/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.action;

import java.sql.Connection;
import java.sql.ResultSet;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import orm.User;
import struts.form.LoginForm;
import dbconnection.MysqlCon;

/** 
 * MyEclipse Struts
 * Creation date: 02-06-2017
 * 
 * XDoclet definition:
 * @struts.action path="/login" name="loginForm" input="/index.jsp" scope="request" validate="true"
 */
public class LoginAction extends ResultBasedAction {
	

	@Override
	public Result execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request) throws Exception {
		// TODO Auto-generated method stub
LoginForm loginForm = (LoginForm) form;// TODO Auto-generated method stub
		
		String username = loginForm.getUsername();
		String password = loginForm.getPassword();
		MysqlCon mysqlCon = new MysqlCon();
		Connection conn=mysqlCon.connection();
		ResultSet rs=mysqlCon.query("select * from user where userName='"+username+"'",conn);
		String msg;
		if (rs==null) {
			System.out.println("无此用户，请重试");
			msg = "无此用户，请重试";
		}
		
		else {
			String correctPassword = rs.getString(3);
			if (!password.equals(correctPassword)){
				System.out.println("密码错误，请重试");
				msg = "密码错误，请重试";
				
			}
			else {
				System.out.println("登录成功！");
				User u = new User();
				u.setUserId(rs.getInt(1));
				u.setUserName(username);
//				u.setPassword(password);
				request.getSession().setAttribute("user", u);
				msg = "登录成功！";
			}
			
		}
		
//		return null;
		conn.close();
		StringResult string = new StringResult(msg);
		return string;
	}
	
}