/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.action.sale;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import dbconnection.MysqlCon;
import entity.Customer;

/** 
 * MyEclipse Struts
 * Creation date: 02-02-2017
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class CustomerListAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		List<Customer> customerlist=new ArrayList<Customer>();
		try{
			int id=0;
			MysqlCon msq=new MysqlCon();
			Connection conn=msq.connection();
			ResultSet rs=msq.query("select * from amc.customer", conn);
			rs.beforeFirst();
			while(rs.next()){
				id=id+1;
				Customer customer=new Customer();
				customer.setId(id+"");
				customer.setCustomerid(rs.getInt(1)+"");
				customer.setCustomername(rs.getString(2));
				customer.setAddress(rs.getString(3));
				customer.setTelephone(rs.getString(4));
				customer.setEmail(rs.getString(5));
				customer.setCreditrank(rs.getInt(6)+"");
				customerlist.add(customer);
			}request.setAttribute("customerlist", customerlist);
			conn.close();
			return mapping.findForward("customerlist");
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		return null;
	}
}