/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.action.sale;

import java.io.UnsupportedEncodingException;
import java.sql.Connection;
import java.sql.ResultSet;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import struts.action.Result;
import struts.action.ResultBasedAction;
import struts.action.StringResult;
import dbconnection.MysqlCon;

import struts.form.CustomerAddForm;

/** 
 * MyEclipse Struts
 * Creation date: 02-02-2017
 * 
 * XDoclet definition:
 * @action.sale validate="true"
 */
public class CustomerAddAction extends ResultBasedAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	
	@Override
	public Result execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request) throws Exception {
		CustomerAddForm customeradd=(CustomerAddForm)form;
		String msg="";
		String customername=customeradd.getCustomername();
		String telephone=customeradd.getTelephone();
		String address=customeradd.getAddress();
		String email=customeradd.getEmail();
		MysqlCon msq=new MysqlCon();
		Connection conn=msq.connection();
		ResultSet rs=msq.query("select * from amc.customer where customerName='"+customername+"'", conn);
		//rs.beforeFirst();
		if(rs!=null){
			msg="已有记录，操作失败！";
			StringResult string = new StringResult(msg);
			conn.close();
			return string;
		}
		else{
		msq.insert("insert into amc.customer(customerName,address,telephone,email,creditRank) values('"+customername+"','"+address+"','"+telephone+"','"+email+"',"+5+")");
		msg="数据插入成功！";
		StringResult string = new StringResult(msg);
		return string;
		}
	}
}