/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.action.sale;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import dbconnection.MysqlCon;

/** 
 * MyEclipse Struts
 * Creation date: 02-02-2017
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class CustomerUpdate1Action extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		String id=request.getParameter("id");
		String customername="";
		String address="";
		String telephone="";
		String email="";
		String creditrank="";
		try{
		MysqlCon msq=new MysqlCon();
		Connection conn=msq.connection();
		ResultSet rs=msq.query("select * from amc.customer where customerID="+id, conn);
		
			rs.beforeFirst();
			while(rs.next()){
				customername=rs.getString(2);
				address=rs.getString(3);
				telephone=rs.getString(4);
				email=rs.getString(5);
				creditrank=rs.getInt(6)+"";
			}
			conn.close();
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		request.setAttribute("customerid", id);
		request.setAttribute("customername", customername);
		request.setAttribute("address", address);
		request.setAttribute("telephone", telephone);
		request.setAttribute("email", email);
		request.setAttribute("creditrank", creditrank);
		return mapping.findForward("customerupdate");
	}
}