/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.action.sale;

import java.io.UnsupportedEncodingException;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;






import struts.action.Result;
import struts.action.ResultBasedAction;
import struts.action.StringResult;

import struts.form.CustomerUpdateForm;

import dbconnection.MysqlCon;

/** 
 * MyEclipse Struts
 * Creation date: 02-02-2017
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class CustomerUpdate2Action extends ResultBasedAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	
	@Override
	public Result execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request) throws Exception {
		String id=request.getParameter("id");
		String customername="";
		String address="";
		String telephone="";
		String email="";
		int creditrank=5;
		String msg="";
		CustomerUpdateForm customerupdate=(CustomerUpdateForm)form;
		customername=customerupdate.getCustomername();
		System.out.println(customername);
		address=customerupdate.getAddress();
		telephone=customerupdate.getTelephone();
		email=customerupdate.getEmail();
		creditrank=Integer.parseInt(customerupdate.getCreditrank());
		MysqlCon msq=new MysqlCon();
		msq.update("update amc.customer set customerName='"+customername+"',address='"+address+"',telephone='"+telephone+"',email='"+email+"',creditrank="+creditrank+" where customerID="+id);
		msg="数据修改成功";
		StringResult string = new StringResult(msg);
		return string;
	}
}