/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.action.sale;

import java.io.UnsupportedEncodingException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;






import struts.action.Result;
import struts.action.ResultBasedAction;
import struts.action.StringResult;

import struts.form.OrderAddForm;

import dbconnection.MysqlCon;
import orm.User;

/** 
 * MyEclipse Struts
 * Creation date: 01-30-2017
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class OrderAdd1Action extends ResultBasedAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	
	@Override
	public Result execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request) throws Exception {
		String msg="";
		OrderAddForm orderadd=(OrderAddForm)form;
		String customername="";
		String address="";
		String person="";
		Date time=new Date();
		SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
		String orderdate=sdf.format(time);
		System.out.println(orderdate);
		HttpSession session = request.getSession();
		User user=(User)session.getAttribute("user");
		Integer userid=user.getUserId();
		int customerid = 0;
		customername =orderadd.getSelect_cus();
		System.out.println(customername);
		address=orderadd.getAddress();
		person=orderadd.getPerson();;
		try{
			MysqlCon msq=new MysqlCon();
			Connection conn=msq.connection();
			ResultSet rs=null;
			//System.out.println("select customerID from customer where customerName='"+customername+"';");
			rs=msq.query("select * from customer where customerName='"+customername+"'", conn);
			rs.beforeFirst();
			while(rs.next()){
				System.out.println(rs.getInt(1));
			customerid=rs.getInt(1);
			}
			conn.close();
		}catch (SQLException e) {
			msg="数据查询失败";
			e.printStackTrace();
		}
		MysqlCon msq=new MysqlCon();
		System.out.println("insert into amc.order(customerID,orderDate,receiveAddress,receiveMan,userID,orderState) values("+customerid+","+time+",'"+address+"','"+person+"',"+userid+",'未处理')");
		msq.insert("insert into amc.order(customerID,orderDate,receiveAddress,receiveMan,userID,orderState) values("+customerid+",'"+orderdate+"','"+address+"','"+person+"',"+userid+",'未处理')");
		MysqlCon msq2=new MysqlCon();
		Connection conn=msq2.connection();
		ResultSet rs=null;
		rs=msq2.query("select * from amc.order where orderDate='"+orderdate+"'", conn);
		int orderid = 0;
		try {
			rs.beforeFirst();
			while(rs.next()){
			orderid=rs.getInt(1);
			}
		} catch (SQLException e) {
			e.printStackTrace();
		}
		String[] checkeds=orderadd.getIfchecked();
		String[] demonds=orderadd.getDemond();
		for(int i=0;i<checkeds.length;i++){
				System.out.println(checkeds[i]);
				String[] s=checkeds[i].split(",");
				Float demond=Float.parseFloat(demonds[Integer.parseInt(s[0])-1]);
				String productid=s[1];
				msq2.insert("insert into orderdetail(orderID,productID,amount,orderDetailState) values("+orderid+","+productid+","+demond+",'未处理')");
		}
		;
		msg="数据插入成功";
		StringResult string = new StringResult(msg);
		return string;
	}
}