/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.action.sale;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import dbconnection.MysqlCon;

import entity.Order;

/** 
 * MyEclipse Struts
 * Creation date: 01-31-2017
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class OrderListAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		List<Order> orderlist=new ArrayList<Order>();
		ResultSet rs=null;
		int ids=0;
		try{
			MysqlCon msq=new MysqlCon();
			Connection conn=msq.connection();
			rs=msq.query("select order.orderID,customer.customerName,order.orderDate,order.orderState from amc.order,amc.customer where amc.order.customerID=amc.customer.customerID",conn);
			rs.beforeFirst();
			while(rs.next()){
				Order order=new Order();
				ids=ids+1;
				order.setIds(ids+"");
				order.setOrderid(rs.getInt(1)+"");
				order.setCustomername(rs.getString(2));
				order.setOrderdate(rs.getDate(3)+"");
				order.setOrderstate(rs.getString(4));
				orderlist.add(order);
			}
			request.setAttribute("orderlist", orderlist);
			conn.close();
		}catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		return mapping.findForward("orderlist");
	}
}