/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.action.financial;

import java.text.SimpleDateFormat;
import java.util.Date;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import dbconnection.MysqlCon;
import struts.action.Result;
import struts.action.ResultBasedAction;
import struts.action.StringResult;
import struts.form.ConfirmPayForm;

/** 
 * MyEclipse Struts
 * Creation date: 02-13-2017
 * 
 * XDoclet definition:
 * @struts.action path="/confirmPay" name="confirmPayForm" scope="request" validate="true"
 */
public class ConfirmPayAction extends ResultBasedAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */

	@Override
	public Result execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request) throws Exception {
		// TODO Auto-generated method stub
		ConfirmPayForm confirmPayForm = (ConfirmPayForm) form;
		int payableID = confirmPayForm.getPayableID();
		float totalAccount = confirmPayForm.getTotalAccount();
		int currentUser = confirmPayForm.getCurrentUser();
		String result;
		try{
			MysqlCon mysqlCon = new MysqlCon();
			mysqlCon.update("UPDATE payable SET payState='ÒÑ¸¶¿î' WHERE payableID="+payableID);
			
			Date date = new Date();
			SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss"); 
			String dateString = formatter.format(date);
			
			mysqlCon.insert("INSERT INTO purchaseaccount (payableID, addTime, totalAccount, "
					+ "userID) VALUES ("+payableID+", '"+dateString+"',"+totalAccount+", "+currentUser+")");
			result="SUCCESS";
			
		}catch(Exception e){
			result="ERROR";
		}
		StringResult sr = new StringResult(result);
		
		return sr;
	}
}