/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.action.financial;

import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.util.Date;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import dbconnection.MysqlCon;
import struts.action.Result;
import struts.action.ResultBasedAction;
import struts.action.StringResult;
import struts.form.ConfirmReceiveForm;

/** 
 * MyEclipse Struts
 * Creation date: 02-11-2017
 * 
 * XDoclet definition:
 * @struts.action path="/confirmReceive" name="confirmReceiveForm" scope="request" validate="true"
 */
public class ConfirmReceiveAction extends ResultBasedAction {
	/*
	 * Generated Methods
	 */

	@Override
	public Result execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request) throws Exception {
		// TODO Auto-generated method stub
		ConfirmReceiveForm confirmReceiveForm = (ConfirmReceiveForm) form;// TODO Auto-generated method stub
		int receivableID = confirmReceiveForm.getReceivableID();
		float totalAccount = confirmReceiveForm.getTotalAccount();
		int currentUser = confirmReceiveForm.getCurrentUser();
		String result;
		try{
			MysqlCon mysqlcon = new MysqlCon();
			mysqlcon.update("update receivable set payState='ÒÑ¸¶¿î' where receivableID="+receivableID);
			
			Date date = new Date();
			SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss"); 
			String dateString = formatter.format(date);
			String sql = "insert into saleaccount (receivableID, addTime, totalAccount, userID) va"
					+ "lues ("+receivableID+", '"+dateString+"', "+totalAccount+", "+currentUser+")";
			System.out.print(sql);
			mysqlcon.insert(sql);
			
			result="SUCCESS";
			
		}catch (Exception e){
			result="ERROR";
		}
		
		StringResult sr = new StringResult(result);
		return sr;
	}
}