/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.action.financial;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import orm.Payabledetail;
import dbconnection.MysqlCon;
import struts.form.PayableDetailForm;

/** 
 * MyEclipse Struts
 * Creation date: 02-12-2017
 * 
 * XDoclet definition:
 * @struts.action path="/payableDetail" name="payableDetailForm" scope="request" validate="true"
 */
public class PayableDetailAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 * @throws SQLException 
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws SQLException {
		PayableDetailForm payableDetailForm = (PayableDetailForm) form;// TODO Auto-generated method stub
		int payableID = payableDetailForm.getPayableID();
		String addTime = payableDetailForm.getAddTime();
		String invoiceRange = payableDetailForm.getInvoiceRange();
		float totalAccount = payableDetailForm.getTotalAccount();
		String payState = payableDetailForm.getPayState();
		String userName = payableDetailForm.getUserID();
		
		HttpSession s = request.getSession();
		s.setAttribute("payableID", payableID);
		s.setAttribute("addTime", addTime);
		s.setAttribute("invoiceRange", invoiceRange);
		s.setAttribute("totalAccount", totalAccount);
		s.setAttribute("payState", payState);
		s.setAttribute("userName", userName);
		
		MysqlCon mysqlCon = new MysqlCon();
		Connection conn = mysqlCon.connection();
		ResultSet rs = mysqlCon.query("select payableDetailID,payableID,productID,salePrice,productName,importNum,totalAccount from payabledetail where payableID="+payableID, conn);
		List pdList = new ArrayList();
		if (rs!=null){
			int counter=0;
			do{
				Payabledetail pd = new Payabledetail();
				pd.setPayableDetailId(++counter);
				pd.setProductID(rs.getInt(3));
				pd.setSalePrice(rs.getFloat(4));
				pd.setProductName(rs.getString(5));
				pd.setImportNum(rs.getFloat(6));
				pd.setTotalAccount(rs.getFloat(7));
				pdList.add(pd);
			}while(rs.next());
		}
		
		s.setAttribute("payableDetailList", pdList);
		
		return null;
	}
}