/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.action.financial;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import orm.Purchaseaccount;
import dbconnection.MysqlCon;

/** 
 * MyEclipse Struts
 * Creation date: 02-13-2017
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class PuchaseAccountAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 * @throws SQLException 
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws SQLException {
		// TODO Auto-generated method stub
		MysqlCon mysqlCon = new MysqlCon();
		Connection conn = mysqlCon.connection();
		ResultSet rs = mysqlCon.query("select payableID,addTime,totalAccount,staffName "
				+ "from purchaseaccount, user, staff where purchaseaccount.userID=user.userID and user.staffID=staff.staffID", conn);
		List paList = new ArrayList();
		int counter=0;
		if (rs!=null) {
			do{
				Purchaseaccount pa = new Purchaseaccount();
				pa.setPurchaseAccountId(++counter);
				pa.setPayableID(rs.getInt(1));
				Timestamp ts = rs.getTimestamp(2);
				SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
				pa.setAddTime(formatter.format(ts));
				pa.setTotalAccount(rs.getFloat(3));
				pa.setStaffName(rs.getString(4));
				paList.add(pa);
				
			}while(rs.next());
		}
		
		request.getSession().setAttribute("purchaseAccountList", paList);
		
		return mapping.findForward("purchaseAccount");
	}
}