/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.action.financial;

import java.sql.Connection;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import net.sf.json.JSONArray;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import dbconnection.MysqlCon;
import struts.action.JsonResult;
import struts.action.Result;
import struts.action.ResultBasedAction;
import struts.form.ReceivableDetailForm;

/** 
 * MyEclipse Struts
 * Creation date: 02-09-2017
 * 
 * XDoclet definition:
 * @struts.action path="/receivableDetail" name="receivableDetailForm" input="/form/receivableDetail.jsp" scope="request" validate="true"
 */
public class ReceivableDetailAction extends ResultBasedAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	
	@Override
	public Result execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request) throws Exception {
		// TODO Auto-generated method stub
		ReceivableDetailForm receivableDetailForm = (ReceivableDetailForm) form;
		int receivableId = receivableDetailForm.getReceivableId();
		MysqlCon mysqlCon = new MysqlCon();
		Connection conn = mysqlCon.connection();
		ResultSet rs = mysqlCon.query("select * from receivabledetail where receivableID="+ receivableId, conn);
		List data = new ArrayList();
		do{
			Map map = new HashMap();
			map.put("receivableDetailID", rs.getInt(1));
			map.put("receivableID", rs.getInt(2));
			map.put("productID", rs.getInt(3));
			map.put("productName", rs.getString(4));
			map.put("salePrice",rs.getFloat(5));
			map.put("saleAmount", rs.getFloat(6));
			map.put("totalAccount", rs.getFloat(7));
			
			data.add(map);
			
		}while(rs.next());
		JSONArray json = JSONArray.fromObject(data);
		JsonResult jsonResult = new JsonResult(json);
		conn.close();
		
		return jsonResult;
	}
}