/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.action.human;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;



import struts.form.UserListForm;

import dbconnection.MysqlCon;
import entity.User;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.*;

/** 
 * MyEclipse Struts
 * Creation date: 01-25-2017
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class UserListAction extends Action {
	
	
	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		
		
		List<User> userlist=new ArrayList<User>();
		ResultSet rs=null;
		try {
			MysqlCon msq=new MysqlCon();
			Connection conn=msq.connection();
			rs=msq.query("select user.userID,user.userName,staff.staffName,staff.department,staff.staffTitle from user,staff where user.staffID=staff.staffID",conn);
			rs.beforeFirst();
			while(rs.next()){
				User u=new User();
				u.setUserid(rs.getInt(1)+"");
				u.setUsername(rs.getString(2));
				u.setStaffname(rs.getString(3));
				u.setDepartment(rs.getString(4));
				u.setTitle(rs.getString(5));
				System.out.println(u.getUserid());
				System.out.println(u.getUsername());
				System.out.println(u.getStaffname());
				System.out.println(u.getDepartment());
				System.out.println(u.getTitle());
				userlist.add(u);	
			}
			request.setAttribute("userlist", userlist);
			conn.close();
			return mapping.findForward("userlist");
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		return null;
	}
}