/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.action.human;

import java.sql.ResultSet;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import struts.action.Result;
import struts.action.ResultBasedAction;
import struts.action.StringResult;
import dbconnection.MysqlCon;

/** 
 * MyEclipse Struts
 * Creation date: 01-25-2017
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class UserDelAction extends ResultBasedAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */


	@Override
	public Result execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request) throws Exception {
		// TODO Auto-generated method stub
		String msg = "";
		try{
			String id=request.getParameter("id");
			MysqlCon msq=new MysqlCon();
			msq.delete("delete from user where userID="+id);
			msg="SUCCESS";
		}catch(Exception e){
			msg="≤Ÿ◊˜ ß∞‹£¨«Î÷ÿ ‘°£";
		}
		
		StringResult sr = new StringResult(msg);
		return sr;
	}
}