/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.action.human;

import java.io.UnsupportedEncodingException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;






import struts.action.Result;
import struts.action.ResultBasedAction;
import struts.action.StringResult;

import struts.form.UserAddForm;

import dbconnection.MysqlCon;

/** 
 * MyEclipse Struts
 * Creation date: 01-28-2017
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class UserAddAction extends ResultBasedAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	

	@Override
	public Result execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request) throws Exception {
		String msg="操作失败";
		UserAddForm useradd=(UserAddForm)form;
		String username= useradd.getUsername();
		String password=useradd.getPassword();
		String staffname=useradd.getStaffname();
		String department=useradd.getDepartment();
		String title=useradd.getStafftitle();
		MysqlCon msq=new MysqlCon();
		Connection conn=msq.connection();
		ResultSet rs=msq.query("select * from amc.user where userName='"+username+"'", conn);
		//rs.beforeFirst();
		if(rs!=null){
			msg="已有记录，操作失败";
			StringResult string=new StringResult(msg);
			conn.close();
			return string;
		}
		else{
		msq.insert("insert into user(userName,password) values('"+username+"','"+password+"')");
		msq.insert("insert into staff(staffName,department,staffTitle) values('"+staffname+"','"+department+"','"+title+"')");
		 rs=msq.query("select staffID from staff where staffName='"+staffname+"'",conn);
		try {
			Integer id=rs.getInt(1);
			System.out.println("update user set staffID="+id+" where userName='"+username+"'");
			msq.update("update user set staffID="+id+" where userName='"+username+"'");
			conn.close();
			msg="操作成功！";
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		StringResult string=new StringResult(msg);
		return string;
		}
	}
}