/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.action.human;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import dbconnection.MysqlCon;

/** 
 * MyEclipse Struts
 * Creation date: 01-28-2017
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class UserUpdate1Action extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		
		String id=request.getParameter("id");
		String username="";
		String staffname="";
		String department="";
		String stafftitle="";
		MysqlCon msq=new MysqlCon();
		Connection conn;
		try {
			conn = msq.connection();
	
		ResultSet rs=msq.query("select userName,staffName,department,staffTitle from user,staff where user.staffID=staff.staffID and userID="+id,conn);
	    
			username=rs.getString(1);
			staffname=rs.getString(2);
			department=rs.getString(3);
			stafftitle=rs.getString(4);
			conn.close();
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}	
	    request.setAttribute("userid",id);
	    request.setAttribute("username",username);
	    request.setAttribute("staffname",staffname);
	    request.setAttribute("department",department);
	    request.setAttribute("stafftitle",stafftitle);
	    System.out.println(username);
		return mapping.findForward("userupdate");
	}
}