/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.action.storage;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import dbconnection.MysqlCon;
import entity.AgainorderDetail;
import entity.Product;

/** 
 * MyEclipse Struts
 * Creation date: 02-08-2017
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class AgainOrderAddAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		try{
		MysqlCon msq=new MysqlCon();
		List<Product> againorder=new ArrayList<Product>();
		Connection conn=msq.connection();
		int number=0;
		ResultSet rs=msq.query("select product.productID,product.productName,product.productSize,product.safeNum from amc.product where product.state='Õý³£' and product.amount<=product.safeNum",conn);
			rs.beforeFirst();
			while(rs.next()){
				Product product=new Product();
				number=number+1;
				product.setIds(number+"");
				product.setProductid(rs.getInt(1)+"");
				product.setProductname(rs.getString(2));
				product.setProductsize(rs.getString(3));
				product.setSafenum(rs.getFloat(4)+"");
				againorder.add(product);
			}
			conn.close();
			request.setAttribute("againorder", againorder);
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		return mapping.findForward("againorderadd");
	}
}