/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.action.storage;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import dbconnection.MysqlCon;
import entity.Import;

/** 
 * MyEclipse Struts
 * Creation date: 02-04-2017
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class ImportListAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		List<Import> importlist=new ArrayList<Import>();
		int ids=0;
		try{
			MysqlCon msq=new MysqlCon();
			Connection conn=msq.connection();
			ResultSet rs=msq.query("select importpd.importPdID,user.userName,importpd.addTime,importpd.state from amc.importpd,amc.user where importpd.userID=user.userID order by importpd.addTime DESC", conn);
		    rs.beforeFirst();
			while(rs.next()){
				ids=ids+1;
				Import importpd=new Import();
				importpd.setIds(ids+"");
				importpd.setImportid(rs.getInt(1)+"");
				importpd.setUsername(rs.getString(2));
				importpd.setImporttime(rs.getDate(3)+"");
				importpd.setImportstate(rs.getString(4));
				importlist.add(importpd);
			}
			request.setAttribute("importlist", importlist);
			conn.close();
		}catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}		return mapping.findForward("importlist");
	}
}