/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.action.storage;

import java.io.UnsupportedEncodingException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import dbconnection.MysqlCon;
import entity.ImportDetail;


/** 
 * MyEclipse Struts
 * Creation date: 02-04-2017
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class ImportOperationAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		String importid=request.getParameter("id");
		String importstate=request.getParameter("state");
		try {
			importstate=new String(importstate.getBytes("ISO-8859-1"),"utf-8");
		} catch (UnsupportedEncodingException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		try{
			MysqlCon msq=new MysqlCon();
			Connection conn=msq.connection();
			ResultSet rs=msq.query("select user.userName,importpd.addTime,importpd.state from amc.importpd,amc.user where importpd.userID=user.userID and importpd.importPdID="+importid,conn);
			rs.beforeFirst();
			while(rs.next()){
				request.setAttribute("importid", importid);
				request.setAttribute("username", rs.getString(1));
				request.setAttribute("importtime", rs.getDate(2)+"");
				request.setAttribute("importstate", rs.getString(3));
			}conn.close();
		}catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		List<ImportDetail> importdetail=new ArrayList<ImportDetail>();
		int id=0;
		try{
			MysqlCon msq=new MysqlCon();
			Connection conn=msq.connection();
			ResultSet rs=msq.query("select importpddetail.productID,product.productName,product.productSize,supplier.supplierCode,importpddetail.importNum from amc.importpddetail,amc.product,amc.supplier where importpddetail.productID=product.productID and product.supplierID=supplier.supplierID and importpddetail.importPdID="+importid, conn);
			rs.beforeFirst();
			while(rs.next()){
				ImportDetail importd=new ImportDetail();
				id=id+1;
				importd.setIds(id+"");
				importd.setProductid(rs.getInt(1)+"");
				importd.setProductname(rs.getString(2));
				importd.setProductsize(rs.getString(3));
				importd.setSuppliercode(rs.getString(4));
				importd.setImportnum(rs.getFloat(5)+"");
				importdetail.add(importd);
			}conn.close();
		    request.setAttribute("importdetail", importdetail);
		}catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		if(importstate.equals("“—¥¶¿Ì"))
			return mapping.findForward("importview");
		else
		    return mapping.findForward("importoperation");
	}
}