/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.action.storage;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import dbconnection.MysqlCon;

import entity.Picking;

/** 
 * MyEclipse Struts
 * Creation date: 02-03-2017
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class PickingListAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		List<Picking> pickinglist=new ArrayList<Picking>();
		int ids=0;
		try{
			MysqlCon msq=new MysqlCon();
			Connection conn=msq.connection();
			ResultSet rs=msq.query("select * from amc.picking", conn);
			rs.beforeFirst();
			while(rs.next()){
				ids=ids+1;
				Picking picking=new Picking();
				picking.setIds(ids+"");
				picking.setPickingid(rs.getInt(1)+"");
				picking.setOrderid(rs.getInt(2)+"");
				picking.setPickingtime(rs.getDate(4)+"");
				picking.setPickingstate(rs.getString(5));
				pickinglist.add(picking);
			}
			request.setAttribute("pickinglist", pickinglist);
			conn.close();
		}catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		return mapping.findForward("pickinglist");
	}
}