/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.action.storage;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import dbconnection.MysqlCon;
import entity.Supplier;

/** 
 * MyEclipse Struts
 * Creation date: 02-07-2017
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class ProductUpdate1Action extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		String id=request.getParameter("id");
		try{
		MysqlCon msq=new MysqlCon();
		Connection conn=msq.connection();
		ResultSet rs=msq.query("select product.productID,product.productName,product.productSize,product.salePrice,product.amount,supplier.supplierID,supplier.supplierCode,product.safeNum from amc.product,amc.supplier where productID="+id+" and product.supplierID=supplier.supplierID", conn);
			rs.beforeFirst();
			while(rs.next()){
				request.setAttribute("id", id);
				request.setAttribute("productid", rs.getInt(1));
				request.setAttribute("productname", rs.getString(2));
				request.setAttribute("productsize", rs.getString(3));
				request.setAttribute("saleprice", rs.getFloat(4)+"");
				request.setAttribute("amount", rs.getFloat(5)+"");
				request.setAttribute("supplier",rs.getInt(6));
				request.setAttribute("safenum", rs.getFloat(8)+"");
			}
		
		rs=msq.query("select supplier.supplierID,supplier.supplierCode from amc.supplier", conn);
		List<Supplier> suppliercode=new ArrayList<Supplier>();
		
			rs.beforeFirst();
			while(rs.next()){
				Supplier supplier=new Supplier();
				supplier.setSupplierid(rs.getInt(1)+"");
				supplier.setSuppliercode(rs.getString(2));
				suppliercode.add(supplier);
			}
			request.setAttribute("suppliercode", suppliercode);
			conn.close();
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		return mapping.findForward("productupdate");
	}
}