/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.action.storage;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import dbconnection.MysqlCon;
import entity.Supplier;

/** 
 * MyEclipse Struts
 * Creation date: 02-07-2017
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class ProductAdd1Action extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		MysqlCon msq=new MysqlCon();
		
		try {
			Connection conn=msq.connection();
			ResultSet rs=msq.query("select supplier.supplierID,supplier.supplierCode from amc.supplier", conn);
			List<Supplier> suppliercode=new ArrayList<Supplier>();
			rs.beforeFirst();
			while(rs.next()){
				Supplier supplier=new Supplier();
				supplier.setSupplierid(rs.getInt(1)+"");
				supplier.setSuppliercode(rs.getString(2));
				suppliercode.add(supplier);
			}
			request.setAttribute("suppliercode", suppliercode);
			conn.close();
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		return mapping.findForward("productadd");
	}
}