/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.action.storage;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import dbconnection.MysqlCon;
import struts.action.Result;
import struts.action.ResultBasedAction;
import struts.action.StringResult;


/** 
 * MyEclipse Struts
 * Creation date: 02-05-2017
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class StorageUpdateAction extends ResultBasedAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	

	@Override
	public Result execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request) throws Exception {
		String msg="操作失败";
		String importid=request.getParameter("id");
		try{
			MysqlCon msq=new MysqlCon();
			Connection conn=msq.connection();
			msq.update("update importpd set state='已处理' where importPdID="+importid);
			ResultSet rs=msq.query("select importpddetail.productID,product.amount,importpddetail.importNum,product.safeNum from amc.product,amc.importpddetail where importpddetail.productID=product.productID and importpddetail.importPdID="+importid,conn);
			rs.beforeFirst();
			while(rs.next()){
				msq.update("update amc.product set amount="+(rs.getFloat(2)+rs.getFloat(3))+" where productID="+rs.getInt(1));
			    if((rs.getFloat(2)+rs.getFloat(3))>rs.getFloat(4))
			    	msq.update("update amc.product set state='正常' where productID="+rs.getInt(1));
			}conn.close();
			msg="操作成功！";
		}catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		StringResult string=new StringResult(msg);
		return string;
	}
}