/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 02-08-2017
 * 
 * XDoclet definition:
 * @struts.form name="againOrderAddForm"
 */
public class AgainOrderAddForm extends ActionForm {
	private String[] productid;
	private String[] demond;
	
	/*
	 * Generated Methods
	 */

	public String[] getProductid() {
		return productid;
	}

	public void setProductid(String[] productid) {
		this.productid = productid;
	}

	public String[] getDemond() {
		return demond;
	}

	public void setDemond(String[] demond) {
		this.demond = demond;
	}

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}
}