/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 02-11-2017
 * 
 * XDoclet definition:
 * @struts.form name="confirmReceiveForm"
 */
public class ConfirmReceiveForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** receivableID property */
	private int receivableID;
	private float totalAccount;
	private int currentUser;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the receivableID.
	 * @return int
	 */
	public int getReceivableID() {
		return receivableID;
	}

	/** 
	 * Set the receivableID.
	 * @param receivableID The receivableID to set
	 */
	public void setReceivableID(int receivableID) {
		this.receivableID = receivableID;
	}

	public float getTotalAccount() {
		return totalAccount;
	}

	public void setTotalAccount(float totalAccount) {
		this.totalAccount = totalAccount;
	}

	public int getCurrentUser() {
		return currentUser;
	}

	public void setCurrentUser(int currentUser) {
		this.currentUser = currentUser;
	}
}