/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 02-13-2017
 * 
 * XDoclet definition:
 * @struts.form name="confirmPayForm"
 */
public class ConfirmPayForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** currentUser property */
	private int currentUser;

	/** payableID property */
	private int payableID;

	/** totalAccount property */
	private float totalAccount;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the currentUser.
	 * @return int
	 */
	public int getCurrentUser() {
		return currentUser;
	}

	/** 
	 * Set the currentUser.
	 * @param currentUser The currentUser to set
	 */
	public void setCurrentUser(int currentUser) {
		this.currentUser = currentUser;
	}

	/** 
	 * Returns the payableID.
	 * @return int
	 */
	public int getPayableID() {
		return payableID;
	}

	/** 
	 * Set the payableID.
	 * @param payableID The payableID to set
	 */
	public void setPayableID(int payableID) {
		this.payableID = payableID;
	}

	/** 
	 * Returns the totalAccount.
	 * @return float
	 */
	public float getTotalAccount() {
		return totalAccount;
	}

	/** 
	 * Set the totalAccount.
	 * @param totalAccount The totalAccount to set
	 */
	public void setTotalAccount(float totalAccount) {
		this.totalAccount = totalAccount;
	}
}