/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 02-05-2017
 * 
 * XDoclet definition:
 * @struts.form name="outstockListForm"
 */
public class OutstockListForm extends ActionForm {
	
	private String number;
	private String outstockid;
	private String orderid;
	private String username;
	private String outstocktime;
	private String outstockstate;
	
	
	/*
	 * Generated Methods
	 */

	public String getNumber() {
		return number;
	}

	public void setNumber(String number) {
		this.number = number;
	}

	public String getOutstockid() {
		return outstockid;
	}

	public void setOutstockid(String outstockid) {
		this.outstockid = outstockid;
	}

	public String getOrderid() {
		return orderid;
	}

	public void setOrderid(String orderid) {
		this.orderid = orderid;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getOutstocktime() {
		return outstocktime;
	}

	public void setOutstocktime(String outstocktime) {
		this.outstocktime = outstocktime;
	}

	public String getOutstockstate() {
		return outstockstate;
	}

	public void setOutstockstate(String outstockstate) {
		this.outstockstate = outstockstate;
	}

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}
}