/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 02-06-2017
 * 
 * XDoclet definition:
 * @struts.form name="outstockDetailForm"
 */
public class OutstockDetailForm extends ActionForm {
	
	private String number;
	private String outstockdetailid;
	private String outstockid;
	private String productid;
	private String productname;
	private String outstocknum;
	
	
	/*
	 * Generated Methods
	 */

	public String getNumber() {
		return number;
	}

	public void setNumber(String number) {
		this.number = number;
	}

	public String getOutstockdetailid() {
		return outstockdetailid;
	}

	public void setOutstockdetailid(String outstockdetailid) {
		this.outstockdetailid = outstockdetailid;
	}

	public String getOutstockid() {
		return outstockid;
	}

	public void setOutstockid(String outstockid) {
		this.outstockid = outstockid;
	}

	public String getProductid() {
		return productid;
	}

	public void setProductid(String productid) {
		this.productid = productid;
	}

	public String getProductname() {
		return productname;
	}

	public void setProductname(String productname) {
		this.productname = productname;
	}

	public String getOutstocknum() {
		return outstocknum;
	}

	public void setOutstocknum(String outstocknum) {
		this.outstocknum = outstocknum;
	}

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}
}