/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 02-12-2017
 * 
 * XDoclet definition:
 * @struts.form name="payableDetailForm"
 */
public class PayableDetailForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** payableID property */
	private int payableID;
	private String addTime;
	private String invoiceRange;
	private float totalAccount;
	private String userID;
	private String payState;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the payableID.
	 * @return int
	 */
	public int getPayableID() {
		return payableID;
	}

	/** 
	 * Set the payableID.
	 * @param payableID The payableID to set
	 */
	public void setPayableID(int payableID) {
		this.payableID = payableID;
	}

	public String getAddTime() {
		return addTime;
	}

	public void setAddTime(String addTime) {
		this.addTime = addTime;
	}

	public String getInvoiceRange() {
		return invoiceRange;
	}

	public void setInvoiceRange(String invoiceRange) {
		this.invoiceRange = invoiceRange;
	}

	public float getTotalAccount() {
		return totalAccount;
	}

	public void setTotalAccount(float totalAccount) {
		this.totalAccount = totalAccount;
	}

	public String getUserID() {
		return userID;
	}

	public void setUserID(String userID) {
		this.userID = userID;
	}

	public String getPayState() {
		return payState;
	}

	public void setPayState(String payState) {
		this.payState = payState;
	}
}