/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 02-09-2017
 * 
 * XDoclet definition:
 * @struts.form name="receivableDetailForm"
 */
public class ReceivableDetailForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** receivableId property */
	private int receivableId;
	private String receivableDate;
	private float totalAccount;
	private String receivableStatus;
	
	

	/*
	 * Generated Methods
	 */

	public String getReceivableDate() {
		return receivableDate;
	}

	public void setReceivableDate(String receivableDate) {
		this.receivableDate = receivableDate;
	}

	public float getTotalAccount() {
		return totalAccount;
	}

	public void setTotalAccount(float totalAccount) {
		this.totalAccount = totalAccount;
	}

	public String getReceivableStatus() {
		return receivableStatus;
	}

	public void setReceivableStatus(String receivableStatus) {
		this.receivableStatus = receivableStatus;
	}

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the receivableId.
	 * @return int
	 */
	public int getReceivableId() {
		return receivableId;
	}

	/** 
	 * Set the receivableId.
	 * @param receivableId The receivableId to set
	 */
	public void setReceivableId(int receivableId) {
		this.receivableId = receivableId;
	}
}