/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 02-06-2017
 * 
 * XDoclet definition:
 * @struts.form name="supplierAddForm"
 */
public class SupplierAddForm extends ActionForm {
	
	private String suppliername;
	private String suppliercode;
	private String suppliermaster;
	private String supplieraddress;
	private String suppliertel;
	private String supplieremail;
	private String productrange;
	
	
	/*
	 * Generated Methods
	 */

	public String getSuppliername() {
		return suppliername;
	}

	public void setSuppliername(String suppliername) {
		this.suppliername = suppliername;
	}

	public String getSuppliercode() {
		return suppliercode;
	}

	public void setSuppliercode(String suppliercode) {
		this.suppliercode = suppliercode;
	}

	public String getSuppliermaster() {
		return suppliermaster;
	}

	public void setSuppliermaster(String suppliermaster) {
		this.suppliermaster = suppliermaster;
	}

	public String getSupplieraddress() {
		return supplieraddress;
	}

	public void setSupplieraddress(String supplieraddress) {
		this.supplieraddress = supplieraddress;
	}

	public String getSuppliertel() {
		return suppliertel;
	}

	public void setSuppliertel(String suppliertel) {
		this.suppliertel = suppliertel;
	}

	public String getSupplieremail() {
		return supplieremail;
	}

	public void setSupplieremail(String supplieremail) {
		this.supplieremail = supplieremail;
	}

	public String getProductrange() {
		return productrange;
	}

	public void setProductrange(String productrange) {
		this.productrange = productrange;
	}

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}
}